language: python
sudo: false
env:
  - AWS_DEFAULT_REGION=us-west-2
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
matrix:
  include:
    - python: 3.6
      env: DEPLOY=true
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
# deploy:
#   provider: pypi
#   user: c.tippett
#   password:
#     secure: SRRxxfZevAfV2u0d+O+SMH5tWLMEJ8tyKDENiCkNf77rHDyRil5vT5qKm0Rv9O+KR80wkbyOGSiWjOyo/HC1dbFJ3v6ZVVo9ER1LX9JzXzqeKe8x68d+4WEl46WaY8aCbN0Te/i/KSlEN8/r9J7AUYFUU3XGvyyrVlQ+uLPipU8ZLCIOOwbnWimYAi1nfXwXj+QnXT+uQCS53mCiP1dIdZvkE2jnSgalVLa9tHxhA/R0/GIBCBgJL7xjcR/30lmyNkj3a9954VsBZBvJPS8rPrKpXJq31C9k07OxiBsE0NhDp/6b/LCldn2+sbSOXNgW8V7Qn2DQjCa7p+qjRNeoNLltJYrzn6CIuXmQjJoiyVba5kvw9poa2bn6l3iJAOJrlqtQ9knc09o+Sj1DqhS8VuEo/TIyx/9QQ6bvbdx9TJ7JF8Tbcmq+fm0cKEUHwPYR/LPwrSDvT+ljUE06gxlCAGELD7MUUQV+j7ph2z8oDLh2Tq3fJu5jOFjHWJeR0Wlq7/kqcM8tVm8B7kKwEOuGcq75ve0VWt1AdXHMP2CC15qeLKBuiqmpMtFbZQEHndPKo+1GLQjBewj6y7SVt4/vVhRh19N6wGCRa4H4yuEjg80oCM2iGPVfSyrXKornYvYPx3bNLZBRaUZIXTgvDn1FPiMaMAIpZzmcZhksZ9uqbHM=
#   distributions: sdist bdist_wheel
#   on:
#     condition: $DEPLOY == true
#     tags: true # only deploy on tagged commits
#     branch: master
#     repo: christippett/ssm_parameter_store
notifications:
  email: false
