version: 2
jobs:
  tox:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: themattrix/tox
    environment:
      AWS_DEFAULT_REGION: "us-west-2"
    steps:
      - checkout
      - run: tox
      - persist_to_workspace:
          root: ./
          paths:
            - .coverage*
  codecov:
    docker:
      - image: python:3.6-slim
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          pip install codecov
          cd /tmp/workspace && codecov
workflows:
  version: 2
  btd:
    jobs:
      - tox
      - codecov:
          requires:
            - tox
