version: 2
jobs:
  test_py36:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: run tests
          environment: TOXENV=py36
          command: tox
  test_py27:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: run tests
          environment: TOXENV=py36
          command: tox
