version: 2
jobs:
  tox:
    docker:
      - image: themattrix/tox
    environment:
      AWS_DEFAULT_REGION: "us-west-2"
    working_directory: ~/ssm_parameter_store
    steps:
      - checkout
      - attach_workspace:
          at: ~/ssm_parameter_store
      - run: tox
      - run: |
          pip install coverage
          coverage combine
          coverage xml
      - persist_to_workspace:
          root: .
          paths: coverage.xml
  codecov:
    machine:
      enabled: true
    working_directory: ~/ssm_parameter_store
    steps:
      - checkout
      - attach_workspace:
          at: ~/ssm_parameter_store
      - run: pip install codecov && codecov --file coverage.xml
workflows:
  version: 2
  btd:
    jobs:
      - tox
      - codecov:
          requires:
            - tox
