version: 2
jobs:
  build:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: themattrix/tox
    environment:
      AWS_DEFAULT_REGION: "us-west-2"
    steps:
      - checkout
      - run: tox
