version: 2
jobs:
  test_py36:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: python:3.6-slim
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: run tests
          environment:
            AWS_DEFAULT_REGION: us-west-2
            TOXENV: py36
          command: tox
  test_py27:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: python:2.7-slim
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: run tests
          environment:
            AWS_DEFAULT_REGION: us-west-2
            TOXENV: py36
          command: tox
workflows:
  version: 2
  build-and-test:
    jobs:
      - test_py36
      - test_py27
