version: 2
jobs:
  test_py36:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: run tests
          environment: TOXENV=py36
          command: |
            pip install tox
            tox
  test_py27:
    working_directory: ~/ssm_parameter_store
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: run tests
          environment: TOXENV=py27
          command: |
            pip install tox
            tox
workflows:
  version: 2
  build-and-test:
    jobs:
      - test_py36
      - test_py27
